import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="px-2 md:px-16 pt-16 min-h-screen antialiased md:py-2 text-white ">
          <Navbar />
          <section className="flex space-x-4 pt-16">
            <div className="">
              <Sidebar />
            </div>
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
